# Generated by Django 3.1.3 on 2024-01-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=149)),
                ('mesg', models.TextField()),
                ('dat_e', models.CharField(max_length=149)),
                ('stz', models.CharField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='pricealert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=149)),
                ('price', models.FloatField()),
                ('email', models.CharField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=149)),
                ('price', models.CharField(max_length=149)),
                ('company', models.CharField(max_length=249)),
                ('dat_e', models.CharField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=149)),
                ('URL', models.TextField()),
                ('Category', models.CharField(max_length=249)),
                ('name', models.TextField()),
                ('img', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=149)),
                ('review', models.TextField()),
                ('rating', models.FloatField()),
                ('name', models.CharField(max_length=149)),
                ('email', models.CharField(max_length=149)),
                ('sentiment', models.CharField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=149)),
                ('email', models.CharField(max_length=149)),
                ('password', models.CharField(max_length=149)),
                ('phone', models.CharField(max_length=149)),
            ],
        ),
    ]
